### ISSUE TITLE
ModuleNotFoundError: No module named 'app'

### ISSUE THREAD

**Issue by LavenderMP** [Youngestdev/async-fastapi-mongo#2]
Hey man I'm following alone of your tutorial, greate stuff but I'm stucking at this error
`~/Documents/Work/OMZ/async-fastapi-mongo/app master
fastapi ❯ python main.py 
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [4440] using watchgod
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/Users/lavendermp/anaconda3/envs/fastapi/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/lavendermp/anaconda3/envs/fastapi/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/lavendermp/anaconda3/envs/fastapi/lib/python3.9/site-packages/uvicorn/subprocess.py", line 61, in subprocess_started
    target(sockets=sockets)
  File "/Users/lavendermp/anaconda3/envs/fastapi/lib/python3.9/site-packages/uvicorn/server.py", line 48, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "/Users/lavendermp/anaconda3/envs/fastapi/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/lavendermp/anaconda3/envs/fastapi/lib/python3.9/site-packages/uvicorn/server.py", line 55, in serve
    config.load()
  File "/Users/lavendermp/anaconda3/envs/fastapi/lib/python3.9/site-packages/uvicorn/config.py", line 308, in load
    self.loaded_app = import_from_string(self.app)
  File "/Users/lavendermp/anaconda3/envs/fastapi/lib/python3.9/site-packages/uvicorn/importer.py", line 23, in import_from_string
    raise exc from None
  File "/Users/lavendermp/anaconda3/envs/fastapi/lib/python3.9/site-packages/uvicorn/importer.py", line 20, in import_from_string
    module = importlib.import_module(module_str)
  File "/Users/lavendermp/anaconda3/envs/fastapi/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/lavendermp/Documents/Work/OMZ/async-fastapi-mongo/app/server/app.py", line 3, in <module>
    from app.server.routes.student import router as StudentRouter
ModuleNotFoundError: No module named 'app'
`
any idea to solve it?

**Comment by Youngestdev** [comment]
Sorry! I'm just getting to see this. Please allow me assess this and get back by weekend :-)

**Comment by Youngestdev** [comment]
@LavenderMP, did you make sure to activate the virtual environment? You need to create a virtual environment to be able to run the application., Please do this and let me know how it goes.

**Comment by cauachagas** [comment]
It's simple. Move the `app/main.py` file to the root of the repository

```bash
.
├── app
│   ├── __init__.py
│   └── server
│       ├── app.py
│       ├── database.py
│       ├── models
│       │   └── student.py
│       └── routes
│           └── student.py
├── LICENSE
├── main.py
├── Procfile
├── README.md
└── requirements.txt
```
In `main.py` change to

```python
uvicorn.run("app.server.app:app", host="0.0.0.0", port=8000, reload=True)
```

Run the application 

```bash
python main.py
```
