### ISSUE TITLE
Got error 

### ISSUE THREAD

**Issue by MikeLiDataEngineer** [Youngestdev/async-fastapi-mongo#6]
Got the following error:

(my_venv) [root@centos-s-1vcpu-1gb-intel-nyc1-01 async-fastapi-mongo]# python app/main.py 
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [96543] using statreload
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/usr/lib64/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib64/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/root/my_venv/lib/python3.8/site-packages/uvicorn/subprocess.py", line 62, in subprocess_started
    target(sockets=sockets)
  File "/root/my_venv/lib/python3.8/site-packages/uvicorn/main.py", line 390, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "uvloop/loop.pyx", line 1501, in uvloop.loop.Loop.run_until_complete
  File "/root/my_venv/lib/python3.8/site-packages/uvicorn/main.py", line 397, in serve
    config.load()
  File "/root/my_venv/lib/python3.8/site-packages/uvicorn/config.py", line 278, in load
    self.loaded_app = import_from_string(self.app)
  File "/root/my_venv/lib/python3.8/site-packages/uvicorn/importer.py", line 23, in import_from_string
    raise exc from None
  File "/root/my_venv/lib/python3.8/site-packages/uvicorn/importer.py", line 20, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  **File "/root/my_venv/async-fastapi-mongo/app/server/app.py", line 3, in <module>
    from app.server.routes.student import router as StudentRouter
ModuleNotFoundError: No module named 'app'**

**Comment by MikeLiDataEngineer** [comment]
After running command: export PYTHONPATH=$PWD at project base directory, the problem got solved.
